name: CI and CD

env:
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
     
   
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o out
      
      - name : Zip contents of the folder
        run: zip -r lambda.zip out
      #- name : copy
        #run: cp /home/runner/work/GLLambdadeploypipeline/GLLambdadeploypipeline/lambda.zip ${GITHUB_WORKSPACE}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: artifactfile
          path: out
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: update s3 bucket
        run: aws s3 cp /home/runner/work/GLLambdadeploypipeline/GLLambdadeploypipeline/lambda.zip s3://s3globelife/ --recursive


